// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-TV3n5cC99sCnxBSLS50bwiOsr8aiY4',
    appId: '1:839691420231:web:da098525762ee9aba0a762',
    messagingSenderId: '839691420231',
    projectId: 'chat-app-flutter-8207e',
    authDomain: 'chat-app-flutter-8207e.firebaseapp.com',
    storageBucket: 'chat-app-flutter-8207e.firebasestorage.app',
    measurementId: 'G-GX19W197Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6pQqinQjaO77UCzSzFw9mfqqfHqFcK4',
    appId: '1:839691420231:android:9fa4708cf390e100a0a762',
    messagingSenderId: '839691420231',
    projectId: 'chat-app-flutter-8207e',
    storageBucket: 'chat-app-flutter-8207e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9r19v6i8u977XYg3VHht-DgKYUC5Qyts',
    appId: '1:839691420231:ios:c82b3eabbf790dd5a0a762',
    messagingSenderId: '839691420231',
    projectId: 'chat-app-flutter-8207e',
    storageBucket: 'chat-app-flutter-8207e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9r19v6i8u977XYg3VHht-DgKYUC5Qyts',
    appId: '1:839691420231:ios:c82b3eabbf790dd5a0a762',
    messagingSenderId: '839691420231',
    projectId: 'chat-app-flutter-8207e',
    storageBucket: 'chat-app-flutter-8207e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2-TV3n5cC99sCnxBSLS50bwiOsr8aiY4',
    appId: '1:839691420231:web:07a9e6f75b8d3464a0a762',
    messagingSenderId: '839691420231',
    projectId: 'chat-app-flutter-8207e',
    authDomain: 'chat-app-flutter-8207e.firebaseapp.com',
    storageBucket: 'chat-app-flutter-8207e.firebasestorage.app',
    measurementId: 'G-SRNS5445PT',
  );
}
